In [1]:
import pandas as pd

In [2]:
import scipy

In [3]:
import numpy as np

In [4]:
a=[1, 3.15, True, 'hello']
b=np.array(a)

In [5]:
print(a)
for elm in a:
    print(elm,type(elm))

[1, 3.15, True, 'hello']
1 <class 'int'>
3.15 <class 'float'>
True <class 'bool'>
hello <class 'str'>


In [6]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [7]:
type(a)

list

In [8]:
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim #차원확인

2

In [12]:
b.size # 원소개수

6

In [13]:
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
b=np.array(a,dtype=np.float64) # 정수=> 실수
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
b=b.astype(np.int64) # 실수-> 정수
print(b)

[[1 2 3]
 [4 5 6]]


# 넘파이 배열 인덱싱

In [16]:
arr =np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
print(arr[0])

1


In [18]:
print(arr[3])

4


In [19]:
print(arr[-1])

5


In [20]:
# 2차원 배열 인덱싱

In [21]:
arr_2d=np.array([[1,2,3][4,5,6]])
# 직관적모양
# [1,2,3]
# [4,5,6]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\wl\AppData\Local\Temp/ipykernel_10180/1948452381.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr_2d=np.array([[1,2,3][4,5,6]])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
arr_2d[0,0] # 1행 1열

In [ ]:
arr_2d[1,2] # 2행 3열

In [ ]:
# 배열 슬라이싱
# 한개이상의 연속된 원소 접근시 사용

In [ ]:
arr_2d = np.arange(1,7).reshape(2,3)
print(arr_2d)

In [ ]:
print(arr_2d[0,:])

In [ ]:
print(arr_2d[:,2])

In [22]:
print(arr_2d[:,:2])

NameError: name 'arr_2d' is not defined

In [23]:
import pandas as pd

In [37]:
data ={
    "이름" : ['아이유', '김연아','홍길동','장범준','강감찬'],
    '학과' : ['국문학', '수학', '컴퓨터', '철학', '경영학'],
    '성적' : [ 3.0, 1.0, 3.5, 2.7, 4.0]
}
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}

In [43]:
df=pd.DataFrame(data)
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [45]:
df.to_csv('./student.csv', sep='.', index=False)

In [50]:
df=pd.read_csv('./student.csv', sep='.')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [51]:
# 판다스 원하는 데이터 선택하기
# 1) 슬라이싱

In [52]:
df[1:5]

이름   학과   성적
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [53]:
df[0:3]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5

In [54]:
df[0:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [55]:
df[:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [56]:
# 2) 인덱싱)

In [57]:
# df[1] 안됨

In [58]:
df['이름']

0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

In [59]:
df['학과']

0    국문학
1     수학
2    컴퓨터
3     철학
4    경영학
Name: 학과, dtype: object

In [60]:
# 3) fancy indexing

In [61]:
df[['이름','학과']]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [62]:
fancy_list=['이름','학과']
df[fancy_list]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [63]:
df[['학과','이름']]

학과   이름
0  국문학  아이유
1   수학  김연아
2  컴퓨터  홍길동
3   철학  장범준
4  경영학  강감찬

In [64]:
# 4)  슬라이싱+인덱싱

In [65]:
df[1:3][['학과','이름']]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [66]:
df[['학과','이름']][1:3]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [67]:
# boolean indexing

In [68]:
df[ df['학과']=='수학' ]

이름  학과   성적
1  김연아  수학  1.0

In [69]:
df[ df['성적'] %0.5] ==0 ]

SyntaxError: unmatched ']' (Temp/ipykernel_10180/1314466723.py, line 1)

In [70]:
# 판다스 고급 인덱싱 loc, iloc

In [71]:
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [72]:
type(df.loc[3])

pandas.core.series.Series

In [73]:
df.loc[ [1,3,4] ]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [74]:
df.loc[ [1,3,4], : ]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [75]:
df.loc[ [1,3,4], '이름':'학과']

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [76]:
df.loc[ [1,3,4], ['이름':'학과']

SyntaxError: invalid syntax (Temp/ipykernel_10180/2269106941.py, line 1)

In [77]:
df.iloc[ [1,3,4], 0:2 ]

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [82]:
df.loc[ df['성적']%2!=0, ['이름','학과','성적']]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7