In [ ]:
feature scaling =
1. 표준화 스탠덜다이제이션 standardization 
2. 정규화 노말라이제이션 normalization
레인지 다를때 클린하게하는과정 머신러닝위한




# Mean Normalization

머신러닝 및 데이터 분석에서는 데이터 노멀라이징(정규화, 을 합니다. 
정규화는 데이터의 범위를 0과 1로 변환하여 데이터 분포를 조정하는 방법입니다.
예를 들어 여러개의 feature가 있는데 어떤거는 100 ~ 200사이의 값이고, 어떤거는 -10 ~ 10 사이의 값이고, 어떤거는 -100 ~ 300 사이의 값이라고 해보면, 이 값들을 분석하기 쉽지가 않습니다. 따라서 이런 불편을 줄이기 위해 범주를 일치시키는 작업을 normalization 이라 합니다. 보통은 0 ~ 1 사이의 값으로 범주를 일치시킵니다.



In [3]:
# import NumPy  
import numpy as np

In [4]:
# 1000 x 20 ndarray 배열을,
# 0이상 5001미만(0 ~ 5000) 의 random integers 로 만드세요.



In [8]:
x = np.random.randint(0,5001, (1000,20)) # 5001불포함 구글검색

In [10]:
x

array([[ 862, 3050, 1335, ..., 4817, 4037, 3456],
       [  63,  292, 2579, ..., 3614, 3919, 4059],
       [1742, 4081, 3349, ...,   40, 1548, 2335],
       ...,
       [4177,  506, 3062, ..., 4061, 3293, 3250],
       [3256,  359,  355, ..., 2368, 2236, 2211],
       [1013, 1999, 3110, ..., 3418, 4174, 3051]])

In [ ]:
# print the shape of X


In [5]:
x.shape

(1000, 20)

다음의 mean normalization 식을 이용해서 정규화 하세요.

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

평균과 표준편차를 이용하면, 위의 정규화 식을 사용할 수 있습니다.



In [ ]:
m 뮤 위 평균 // 아래 ai 시그마=표준편차

In [ ]:
# 열별 평균값을 얻어온다

In [6]:
mean_cols = x.mean( axis=0)

In [7]:
mean_cols.shape 

(20,)

In [8]:
mean_cols

array([2473.798, 2577.216, 2467.431, 2460.182, 2432.644, 2595.585,
       2501.208, 2592.878, 2541.66 , 2577.527, 2571.216, 2553.988,
       2413.814, 2403.931, 2584.518, 2509.071, 2516.977, 2408.336,
       2454.09 , 2532.517])

In [ ]:
# 열을 고정하고 각 행에 대한 표준편차, 즉 모든 열별 표준편차값을 얻어온다.


In [9]:
std_cols = x.std(axis=0)

In [10]:
std_cols

array([1403.46740368, 1434.06358274, 1454.1462166 , 1394.9038142 ,
       1460.40971144, 1431.99225095, 1452.26527285, 1437.36556975,
       1425.53966918, 1426.53669959, 1465.06584335, 1406.45196429,
       1467.49734903, 1477.72670147, 1422.68110681, 1446.63010751,
       1462.22025648, 1474.20438241, 1440.46677778, 1424.06721952])

In [11]:
std_cols.shape

(20,)

각 벡터의 shape 을 확인하세요.

In [ ]:
# Print the shape of ave_cols

# Print the shape of std_cols


위 공식대로 노멀라이제이션 하세요.

In [14]:
# Mean normalize X

x_norm = (x-mean_cols) / std_cols  #컬럼별 알아서 계산함

In [15]:
x_norm

array([[-1.42347303,  1.23968283, -1.24363766, ..., -1.00212428,
        -0.66859577, -0.54738778],
       [-0.70382682, -0.94432075,  0.51478248, ...,  1.06543164,
        -0.93101071, -0.58741398],
       [-0.9168706 ,  1.48374453, -0.31388247, ...,  0.11508852,
        -0.93101071,  0.51014656],
       ...,
       [ 0.42836905, -1.08308726,  1.32556752, ...,  0.8524354 ,
        -1.45792325,  0.85001816],
       [ 0.26235166,  0.41266232,  1.26436322, ..., -1.43286509,
         0.79828984,  0.62250081],
       [-0.8897948 ,  1.46700887, -0.30012869, ..., -1.23343549,
         0.76357887, -0.84442432]])

제대로 수행했으면 아마 $X_{\tiny{\mbox{norm}}}$ 배열은 값들이 0 근처의 값들로 나올겁니다.아래를 통해 확인하세요.

In [42]:
# X_norm 을 출력(프린트) 하세요.
x_norm

array([[ 1.29412921, -0.62002032,  0.18154444, ...,  1.576246  ,
         0.26162213,  1.59143751],
       [-1.46574945,  0.85415091,  1.29804792, ..., -0.40058399,
        -0.47126303,  1.5866225 ],
       [ 1.23137228, -1.6013891 ,  1.01805573, ...,  1.7131572 ,
        -0.2595101 , -1.43101242],
       ...,
       [ 0.85697014, -1.26179314, -0.31883763, ...,  1.61396643,
         0.57375145, -0.80368553],
       [ 0.05681927, -1.2434366 , -1.58434685, ...,  1.42676133,
         1.15538452, -0.0745556 ],
       [ 0.04826151, -1.42770801,  0.34441118, ..., -0.11558518,
         1.40563799,  1.66366265]])

In [16]:
# 각 컬럼(열)별 minimum value 를 출력하세요.
x_norm.min(axis=0)

array([-1.76263303, -1.79714207, -1.69682455, -1.75939156, -1.66367286,
       -1.80907753, -1.71814891, -1.80182276, -1.77943838, -1.80403841,
       -1.75092199, -1.81448643, -1.63599205, -1.62609974, -1.81524727,
       -1.73442471, -1.72065528, -1.62958137, -1.7029827 , -1.77696457])

In [17]:
# 각 컬럼(열)별 maximum value 를 출력하세요.
x_norm.max(axis=0)

array([1.79925946, 1.68805904, 1.73405464, 1.82078361, 1.75660021,
       1.67837151, 1.71923962, 1.67189339, 1.72169183, 1.6953458 ,
       1.65438571, 1.73771452, 1.75754048, 1.75679914, 1.69291768,
       1.71151491, 1.69743442, 1.75733028, 1.76533749, 1.73129679])